// TEXT EDITOR
export const SET_TEXT_EDITOR_THEME = 'SET_TEXT_EDITOR_THEME';
export const SET_TEXT_EDITOR_OPTIONS = 'SET_TEXT_EDITOR_OPTIONS';
export const SET_TEXT_EDITOR_VALUE = 'SET_TEXT_EDITOR_VALUE';
export const SET_FONT_SIZE = 'SET_FONT_SIZE';
